---
- name: Install MacOS Packages
  hosts: localhost
  become: false

  tasks:
    
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name:
          - iterm2
        state: present

    - name: Installing Homebrew Packages
      homebrew:
        name:
          - git
          - ansible
          - emacs
          - gnupg
          - terraform
          - golang
          - mplayer
        state: present
        
