---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - iterm2
    brew_packages:      
      - git


 - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name:
          - iterm2
