---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - iterm2
    brew_packages:      
      - git


  tasks:
    
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name:
          - iterm2
        state: present

  - name: Installing Homebrew Packages
      homebrew:
        name:
          - git
          - ansible
          - emacs
          - gnupg
        state: present
        
